#!/bin/bash

# This script gets called by .xinitrc in my dwm config
# So do not delete.

# default sounds is 1
SOUNDCARD=1
# put newline in variable for fstrings compatability
newline=$'\n'


# functions to switch from LVDS1 to VGA and vice versa
function ActivateDock {
    echo "Switching to Dock"
    SOUNDCARD=2
    printstring="defaults.pcm.card ${SOUNDCARD}${newline}defaults.ctl.card ${SOUNDCARD}"
    echo "$printstring" > /etc/asound.conf
}

function DeactivateDock {
    echo "Switching to normal"
    SOUNDCARD=2
    printstring="defaults.pcm.card ${SOUNDCARD}${newline}defaults.ctl.card ${SOUNDCARD}"
    echo "$printstring" > /etc/asound.conf
}

# functions to check if HDMI-0 is connected and in use
function DockActive {
    [ $SOUNDCARD = "2" ]
}
function DockConnected {
    ! cat /proc/asound/cards | grep "sofh" | grep -q 1
}

# actual script
while true
do
        # if ! HDMIActive && ! HDMIConnected 
        # then
        #         ActivateLaptop
        # fi
         
        if ! DockActive && DockConnected
        then
                ActivateDock
        fi

        if DockActive && ! DockConnected
        then
                DeactivateDock
        fi

       sleep 1s
done
